jobs:

  - template: azure-pipelines-unix-buildwheel-template.yml
    parameters:
      name: 'mac_arm_py310'
      vmImage: 'macOS-15-arm64'
      NUMPY_VERSION: '2.0.0'
      CIBW_BUILD: 'cp310-*'
      CIBW_ENVIRONMENT_MACOS: 'HG_USE_TBB=0 NUMPY_VERSION="${{ parameters.NUMPY_VERSION }}"'
      
  - template: azure-pipelines-unix-buildwheel-template.yml
    parameters:
      name: 'mac_arm_py311'
      vmImage: 'macOS-15-arm64'
      NUMPY_VERSION: '2.0.0'
      CIBW_BUILD: 'cp311-*'
      CIBW_ENVIRONMENT_MACOS: 'HG_USE_TBB=0 NUMPY_VERSION="${{ parameters.NUMPY_VERSION }}"'

  - template: azure-pipelines-unix-buildwheel-template.yml
    parameters:
      name: 'mac_arm_py312'
      vmImage: 'macOS-15-arm64'
      NUMPY_VERSION: '2.0.0'
      CIBW_BUILD: 'cp312-*'
      CIBW_ENVIRONMENT_MACOS: 'HG_USE_TBB=0 NUMPY_VERSION="${{ parameters.NUMPY_VERSION }}"'  

  - template: azure-pipelines-unix-buildwheel-template.yml
    parameters:
      name: 'mac_arm_py313'
      vmImage: 'macOS-15-arm64'
      NUMPY_VERSION: '2.1.3'
      CIBW_BUILD: 'cp313-*'
      CIBW_ENVIRONMENT_MACOS: 'HG_USE_TBB=0 NUMPY_VERSION="${{ parameters.NUMPY_VERSION }}"'

  - template: azure-pipelines-unix-buildwheel-template.yml
    parameters:
      name: 'mac_arm_py314'
      vmImage: 'macOS-15-arm64'
      NUMPY_VERSION: '2.3.2'
      CIBW_BUILD: 'cp314-*'
      CIBW_ENVIRONMENT_MACOS: 'HG_USE_TBB=0 NUMPY_VERSION="${{ parameters.NUMPY_VERSION }}"'
      force: true
