jobs:
  - template: azure-pipelines-unix-buildwheel-template.yml
    parameters:
      name: 'linux_py38'
      vmImage: 'ubuntu-22.04'
      CIBW_BUILD: 'cp38-*'
      NUMPY_VERSION: '1.17.5'

  - template: azure-pipelines-unix-buildwheel-template.yml
    parameters:
      name: 'linux_py39'
      vmImage: 'ubuntu-22.04'
      CIBW_BUILD: 'cp39-*'
      NUMPY_VERSION: '1.19.5'

  - template: azure-pipelines-unix-buildwheel-template.yml
    parameters:
      name: 'linux_py310'
      vmImage: 'ubuntu-22.04'
      CIBW_BUILD: 'cp310-*'
      NUMPY_VERSION: '2.0.0'

  - template: azure-pipelines-unix-buildwheel-template.yml
    parameters:
      name: 'linux_py311'
      vmImage: 'ubuntu-22.04'
      CIBW_BUILD: 'cp311-*'
      NUMPY_VERSION: '2.0.0'

  - template: azure-pipelines-unix-buildwheel-template.yml
    parameters:
      name: 'linux_py312'
      vmImage: 'ubuntu-22.04'
      CIBW_BUILD: 'cp312-*'
      NUMPY_VERSION: '2.0.0'
      force: true